manifest_version = "0.1.0"
name = "Default starter for AssemblyScript"
description = "Get to know the Fastly Compute@Edge environment with a basic starter that demonstrates routing, simple synthetic responses and overriding caching rules."
authors = ["<oss@fastly.com>"]
language = "assemblyscript"
